### ISSUE TITLE
MNW2 budget header problem when nmnw2 == 0

### ISSUE THREAD

**Issue by christianlangevin** [MODFLOW-USGS/mf2005#35]
Lenny,

Just wanted to let you know that a bug was introduced in MNW2 in the last version of MODFLOW.  It looks like it is related to one of Scott Boyce's changes and I think it only affects the compact budget option.  Previously, if there were no active MNW2 wells, then a header was not written to the budget file and no individual MNW2 entries were written either.

Scott made a change so that now the header is always written, and this is probably good form, because there is good reason to always write the header, even if there are zero entries in the subsequent list.  But the problem is that if there are no active wells, then no data are written.  So the header is not correct because it indicates that data will follow.  This breaks programs like zonebudget, and anything else that needs to read the budget file.

Rich, it looks like this bug is also in NWT.  

I'm letting you know in case you'd prefer to handle it.  If not, I'd be happy to come up with a solution. Just wanted to let you know.  I think the simple fix is to just do something like this:

C2-----IF CELL-BY-CELL FLOWS WILL BE SAVED AS A LIST, WRITE HEADER.
      IF(IBD.EQ.2) THEN  !swm: check if wells are active; seb removed "nmnw2.gt.0.AND." which was added by swm (11/30/15)
         NAUX=NMNWVL-30
C-LFK         NAUX = 0   !!   Set to zero -- Change order to dump
c         IF(IAUXSV.EQ.0) NAUX=0
         ntotheader = 0
         if (nmnw2.gt.0) ntotheader = ntotnod
         CALL UBDSV4(KSTP,KPER,TEXT,NAUX,MNWAUX,IWL2CB,NCOL,NROW,NLAY,
     1          ntotheader,IOUT,DELT,PERTIM,TOTIM,IBOUND)
      END IF

-C

**Comment by ScottBoyce** [comment]
That was not a bug from me.
It was Lenny that folded in OWHM code incorrectly.

OWHM allows for multiple budget groups, so their is a separate variable that holds the number of nodes used within the group.
`GRPNODE(IG)` rather than `ntotheader`.

When the code was back-merged, it was not done correctly.

I should also point out you still have the error that results in mass problems when MNW2 converges on an odd iteration (HCOF modification) because it the nodes hold the pumping rate from the previous iteration rather than the converged iteration.

This is what MNW2 uses in OWHM:
```
C2-----IF CELL-BY-CELL FLOWS WILL BE SAVED AS A LIST, WRITE HEADER.
      IF(IBD.EQ.2) THEN  !swm: check if wells are active seb removed "nmnw2.gt.0.AND." which was added by swm
         NAUX=NMNWVL-30
C-LFK         NAUX = 0   !!   Set to zero -- Change order to dump
c         IF(IAUXSV.EQ.0) NAUX=0
         CALL UBDSV4(KSTP,KPER,TEXT,NAUX,MNWAUX,IWL2CB,NCOL,NROW,NLAY,
     1          GRPNODE(IG),IOUT,DELT,PERTIM,TOTIM,IBOUND)
      END IF
c  clear the buffer.
      buff=DZ
```
