### ISSUE TITLE
MODFLOW incorrectly identifies an active cell as inactive.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mf2005#47]
[SWR_test2.zip](https://github.com/MODFLOW-USGS/mf2005/files/6861767/SWR_test2.zip)
In the attached model, MODFLOW halts with an error message when a CHD cell is specified. The error message incorrectly states that the IBOUND value for the cell is zero. However, all the cells in the model are active. Although the layer is convertible, the initial heads are above the cell bottom and all the hydraulic conductivities are greater than zero. I suspect that the SWR package is involved because if the SWR package is removed from the model, the model runs to completion (although it has a high percent discrepancy in many time steps).

**Comment by jdhughes-dev** [comment]
The test input file has specified the ISWRONLY variable to be 1, which inactivates all of the groundwater model cells. The ISWRONLY option allows users to run the SWR model without a connected groundwater model. Because there are CHD cells in no inactive cells MODFLOW-2005 terminates with an error. This is the expected behavior and not a bug.
